package io.github.marketplace.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;

import java.util.Date;

/**
 * Created by EalenXie on 2022/3/16 15:51
 */
@Data
public class OrdersDTO {

    /**
     * 必填
     * The Distribution Facility “Distributor ID” which uniquely identifies each facility and is autogenerated during DSV account creation. Every time you add/update a facility in the Supplier Center, a new ID is generated
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer limit;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String sku;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String customerOrderId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String purchaseOrderId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String status;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ssZ")
    private Date createdStartDate;
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ssZ")
    private Date createdEndDate;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String fromExpectedShipDate;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String toExpectedShipDate;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Boolean productInfo;


}
